[tool.black]
line-length = 100
target-version = ['py310']
extend-exclude = '''
/(
  | tmp.*
  | test.*
  | results
  | data
  | vendor
)/
'''

[tool.isort]
profile = "black"
line_length = 100
skip_gitignore = true
