name: fastsurfer-r
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - r-base=4.5
  - make
  - c-compiler
  - cxx-compiler
  - fortran-compiler
  - r-optparse
  - r-jsonlite
  - r-ggplot2
  - r-mgcv
  - r-remotes
  - r-bh
  - r-matrix
  - r-rcpp
  - r-rcpparmadillo
  - black
  - flake8
